config/routes.rb
Rails.application.routes.draw do
  root to: 'pizzas#index'

  get '/pizzas' => 'pizzas#index'
  get '/pizzas/:pizza' => 'pizzas#show', as: :pizza
  post '/pizzas/:pizza/remove/:ingredient' => 'pizzas#remove_ingredient', as: :remove_ingredient
  post '/pizzas/:pizza/add' => 'pizzas#add_ingredient', as: :add_ingredient
  get '/pizzas/:pizza/custom' => 'pizzas#custom', as: :custom
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true

  def self.find_and_sort(ingredients)
    self.order(:name).find(ingredients)
  end

  def self.unused(used)
    self.all.to_a.select do |ingredient|
      !used.include?(ingredient.id)
    end
  end
end

app/models/prepared_pizza.rb
class PreparedPizza < ApplicationRecord
  MANUFACTURE_PRICE = 1.5

  validates :name, presence: true, uniqueness: true

  def self.calculate_price(ingredients)
    ingredients_price = 0.0

    ingredients.each do |ingredient|
      ingredients_price += ingredient.price
    end

    final_price = ingredients_price * MANUFACTURE_PRICE
    final_price
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :ingredient, presence: true
  validates :pizza, presence: true

  def self.ingredients_for(pizza)
    recipes = where(pizza: pizza)

    ingredients = recipes.map do |recipe|
      recipe.ingredient
    end

    ingredients
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :remove_ingredient, :add_ingredient, :custom]
  before_action :get_ingredient_id, only: [:remove_ingredient, :add_ingredient]
  before_action :get_new_ingredients, only: [:show, :custom]

  def index
    @pizzas = PreparedPizza.all
  end

  def show
    default_ingredients = Recipe.ingredients_for(@pizza.id)
    session[:ingredients] = default_ingredients

    @unused_ingredients = Ingredient.unused(default_ingredients)
    @ingredients = Ingredient.find_and_sort(default_ingredients)
    @pizza_price = PreparedPizza.calculate_price(@ingredients)
  end

  def remove_ingredient
    if has_ingredients?
      ingredients.delete(@ingredient_id)
    end

    redirect_to custom_path(@pizza.id)
  end

  def add_ingredient
    ingredients << @ingredient_id

    redirect_to custom_path(@pizza.id)
  end

  def custom
    @unused_ingredients = Ingredient.unused(ingredients)
    @ingredients = Ingredient.find_and_sort(ingredients)
    @pizza_price = PreparedPizza.calculate_price(@ingredients)
  end

  private

  def has_ingredients?
    ingredients.size > 1
  end

  def set_pizza
    @pizza = PreparedPizza.find(params[:pizza])
  end

  def ingredients
    session[:ingredients] || []
  end

  def get_ingredient_id
    id = params[:ingredient][0]

    @ingredient_id = id.to_i
  end

  def get_new_ingredients
    @new_ingredients = Ingredient.all.to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
  def with_currency(price)
    "#{price} €"
  end

  def minimum?(ingredients)
    ingredients.size == 1
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:pizza_manager) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'pizza.ico' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
      <div class="container">
        <a href="/" class="navbar-brand">
          <h1>
            <%= t(:pizza_manager) %>
          </h1>
        </a>
      </div>
    </nav>
    <div class="container margins">
    <%= yield %>
    </div>
    <footer class="py-5 bg-danger">
      <div class="container">
        <p class="m-0 text-center text-white">
          <%= t(:enjoy_your_pizza) %>
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/pizzas/_pizza.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_tag(add_ingredient_path(@pizza.id), class: "float-left") do %>
        <%= collection_select('ingredient', nil, @unused_ingredients, :id, :name, {}, class: "form-control") %>
        <%= submit_tag t(:add), class: 'btn btn-success' %>
      <% end %>
      <%= link_to(t(:reset_ingredients), pizza_path(@pizza.id), class: "float-right btn btn-danger") %>
    </div>
  </div>

  <% if minimum?(@ingredients) %>
    <div class="alert alert-danger" role="alert">
      <%= t(:minimum_ingredients_warning) %>
    </div>
  <% end %>

  <h2><%= t(:ingredients) %></h2>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th><%= t(:ingredient) %></th>
          <th><%= t(:price) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= "#{ingredient.name}: " %></td>
          <td><%= "#{with_currency(ingredient.price)}" %></td>
          <td><%= link_to(t(:remove), remove_ingredient_path(@pizza.id, ingredient.id), { method: :post, id: ingredient.id }) %></td>
        </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td class="float-right"><%= "#{t(:total)}:" %></td>
          <td><%= "#{with_currency(@pizza_price)}" %></td>
          <td></td>
        </tr>
      </tfoot>
    </table>
    <div class="text-center"><%= "(#{t(:manufacture_price_explanation)})" %></div>
  </div>
</div>

<div class="text-center">
  <%= link_to(t(:back), root_path) %>
</div>

app/views/pizzas/custom.html.erb
<h2 class="my-4"><%= "#{t(:custom)} #{@pizza.name}" %></h2>

<%= render 'pizza' %>

app/views/pizzas/custom_pizza.html.erb
<h1><%= "#{t(:custom)} #{@pizza.name}" %></h1>

<p>
  <%= link_to(t(:reset_ingredients), pizza_path(@pizza.id)) %>
</p>

<%= render 'pizza' %>

app/views/pizzas/index.html.erb
<h2 class="my-4"><%= t(:chosse_your_pizza) %>
  <small><%= t(:and_do_it_to_your_liking) %></small>
</h2>
<% @pizzas.each do |pizza| %>
  <div class="row">
    <div class="col-md-5">
      <%= image_tag(pizza.image, class: "img-fluid rounded mb-3 mb-md-0") %>
    </div>
    <div class="col-md-7">
      <h3><%= pizza.name %></h3>
      <p><%= pizza.description %></p>
      <%= link_to(t(:customize), pizza_path(pizza.id), class: "btn btn-success") %>
    </div>
  </div>
<% end %>

app/views/pizzas/show.html.erb
<h2 class="my-4"><%= @pizza.name %></h2>

<%= render 'pizza' %>